mission completed
dromanchuck/tms-js-basic pull request #18
Opened 2020-06-22 17:30 UTC by NikFiery

****Hello, my friends!****
The task is completed.

2020-06-23 15:29 UTC, dromanchuck requested changes

2020-06-23 15:29 UTC, dromanchuck commented on lesson02/homeWork.js
> +let k = (n ** 2) + (m ** 2); // альтернатива(n * n) + (m * m)
Сумма квадрата катетов = сумме квадрата гипотенузы 
Такое чувство что здесь нужен еще корень (Math.sqrt(число))

2020-06-23 15:29 UTC, dromanchuck commented on lesson02/homeWork.js
> +let status = 604800; // Секунд в одной неделе
Честно говоря не верю, я знаю точно что в одной минуте 60 секунд

2020-06-23 15:29 UTC, dromanchuck commented on lesson02/homeWork.js
> +let status = 604800; // Секунд в одной неделе
Попробуй расписать как ты это вычеслил

2020-06-23 15:29 UTC, dromanchuck commented on lesson02/homeWork.js
> +console.log(`'Мне %${age}% лет!'.`);
в обоих случаях лишние внутренние кавычки

2020-06-23 15:29 UTC, dromanchuck commented on lesson02/homeWork.js
> +alert(`Быдо 10 котиков, а из-за магического обряда, стало: ${cat}`);
:)

2020-06-23 15:29 UTC, dromanchuck commented on lesson02/homeWork.js
> +//Задание №10. //"Поместите в них результат выражений" - Это все ? Или нужно перевести ?
все правильно

2020-06-24 15:12 UTC, NikFiery commented on lesson02/homeWork.js
> +console.log(`'Мне %${age}% лет!'.`);
В задании так написано было)
Или ты про `` ?

2020-06-24 15:32 UTC, dromanchuck commented on lesson02/homeWork.js
> +console.log(`'Мне %${age}% лет!'.`);
 В задании так было написано, чтобы дать понять результатом будет строка)

2020-06-24 15:45 UTC, dromanchuck approved these changes

2020-06-30 06:33 UTC, closed without merging