solution
dromanchuck/tms-js-basic pull request #30
Opened 2020-06-30 14:43 UTC by Andrey-Sushkevich

solution for homework

2020-06-30 19:56 UTC, dromanchuck requested changes

2020-06-30 19:56 UTC, dromanchuck commented on lesson03/index.js
> +      alert( 'Знак числа  a1  +' );
алерт нужно использовать в конце, чтобы вывести за один раз все знаки, 
для этого нужно создать переменную и в нее при помощи оператора += добавлять знаки

2020-06-30 19:56 UTC, dromanchuck commented on lesson03/index.js
> +      alert( 'Знак числа  a1  +' );
let result;

if(a1 > 0) {
  result += ''
} else {
  result +='-'
}

...

alert(result);

2020-06-30 19:56 UTC, dromanchuck commented on lesson03/index.js
> +}
для прямугольного треугольника достаточно одно цикла в for внутри while
```
while (i < max) {
    star = "";
    for (j = 0; j < i; j++) star += "*";
    console.log(star);
    i++;
}

2020-06-30 19:56 UTC, dromanchuck commented on lesson03/index.js
> +     while (a!=0 && b!=0)
не забываем про фигурные скобки

2020-06-30 19:56 UTC, dromanchuck commented on lesson03/index.js
> +      alert(a + b);
зачем здесь в выводить a + b ?

2020-06-30 19:56 UTC, dromanchuck commented on lesson03/index.js
> +    **/
отсортировать можно по убыванию или по возрастанию

2020-07-03 07:08 UTC, Andrey-Sushkevich commented on lesson03/index.js
> +      alert( 'Знак числа  a1  +' );
да я понял)  хотел попробовать так для каждого числа

2020-07-03 07:08 UTC, Andrey-Sushkevich commented on lesson03/index.js
> +}
забыл почему -то скинуть вариант для прямоугольного

2020-07-03 07:08 UTC, Andrey-Sushkevich commented on lesson03/index.js
> +     while (a!=0 && b!=0)
ок

2020-07-03 07:18 UTC, Andrey-Sushkevich commented on lesson03/index.js
> +    **/
я думал допустим отсортировать числа можно по признаку допустим чет/нечет . и четные в одну переменную допустим , нечетные в другую)

2021-01-14 16:47 UTC, closed without merging