Zavalo m/lesson14
dromanchuck/tms-js-basic pull request #64
Opened 2020-08-07 10:49 UTC by MichaelZavalo

Hello. I have one question in the second task. Checking the course value does not work? Pls give me feedback and help me solve this question

2020-08-07 17:11 UTC, dromanchuck requested changes

2020-08-07 17:11 UTC, dromanchuck commented on lesson14/homeWork.js
> +    }
В этом классе не нужен конструктор, 
здесь каждый метод будет принимать строку как аргумент

2020-08-07 17:11 UTC, dromanchuck commented on lesson14/homeWork.js
> +    }
здесь должно быть аналогично как и было выше
```
MyString.prototype.ucWords = function(str) {
    let arr = str.split(' ');
    arr.forEach((element,ind,arr) => {
        arr[ind] = this.upperCaseFirst(element);
    });
    return arr.join(' ');
}
```
```
getStrUcWords(str) {
    let arr = str.split(' ');
    arr.forEach((element,ind,arr) => {
        arr[ind] = this.upperCaseFirst(element);
    });
    return arr.join(' ');
}
```

2020-08-07 17:11 UTC, dromanchuck commented on lesson14/homeWork.js
> +        this.surname = surname;
Здесь нужно использовать super, чтобы вызвать конструктор родительского класса User

super(name, surname);
 и поэтому строки
this.name = name;
        this.surname = surname;
здесь не нужны, они выполнятся в конструкторе класса User

2020-08-08 06:12 UTC, MichaelZavalo commented on lesson14/homeWork.js
> +        this.surname = surname;
Понял спасибо

2021-01-14 16:44 UTC, closed without merging