yuryD/lesson15
dromanchuck/tms-js-basic pull request #66
Opened 2020-08-13 13:39 UTC by charleswein

Have a problem with localStorage work after done and second with contains?

2020-08-13 13:41 UTC, charleswein commented
Work js file index1.js

2020-08-14 13:54 UTC, dromanchuck requested changes

2020-08-14 13:54 UTC, dromanchuck commented on lesson15/index1.js
> +  if (p.containsClass('text-done') === false) {
Проблема в том, что в твоем случае название containsClass не равно containsClass в классе 
Paragraph. Похоже это из-за того что в одном из названий есть "с" из кириллицы, а не из латиницы. Обрати на это внимание

2020-08-14 13:54 UTC, dromanchuck commented on lesson15/index1.js
> +  }
Здесь есть логическая ошибка. Какая должна быть логика:
если класс "text-done" есть то надо его добавить выставить имя  "To Do"  и выставить
в соответствующем элементе массива сделать поле done равным true

если класса "text-done" нет то надо его убрать, выставить имя  "Done"  и выставить
в соответствующем элементе массива сделать поле done равным false

2020-08-14 13:54 UTC, dromanchuck commented on lesson15/index1.js
> +  }
Как здесь написано, то делается наоборот

2020-08-15 05:12 UTC, charleswein commented on lesson15/index1.js
> +  if (p.containsClass('text-done') === false) {
Я вроде как их копировал... но проверю(

2021-01-14 16:44 UTC, closed without merging